spring:
  application:
    name: app-t248-weixin
  boot:
    admin:
      client:
        url: http://localhost:8199
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
###服务启动端口号
server:
  port: 8200
####swagger相关配置
swagger:
  base-package: com.t248.weixin.service
  title: 微信服务接口
  description: Spring Cloud项目实践
  version: 1.1
  contact:
    name: 风继续吹
    email: 1366845556@qq.com